- hosts: localhost
  gather_facts: false
  become: yes
  vars:
    roles_dir: "{{ playbook_dir }}/../../roles"
    vars_dir: "{{ playbook_dir }}/role_vars"

  tasks:
  - name: Find all role directories in collection
    find:
      paths: "{{ roles_dir }}"
      file_type: directory
      patterns: "*"
    register: found_roles

  - name: create README for each role specified in found roles
    set_fact:
      role_name: "{{ role_dir.path | basename }}"
      output_path: "{{ roles_dir }}/{{ role_name }}/{{ role_name }}_README.md"
      vars_file: "{{ vars_dir }}/{{ role_name }}_readme_vars.yml"
    loop: "{{ found_roles.files }}"
    loop_control:
      loop_var: role_dir


    
