- hosts: localhost
  gather_facts: false
  become: yes
  vars:
    roles_dir: "{{ playbook_dir }}/../../roles"
    vars_dir: "{{ playbook_dir }}/role_vars"
    exclude_roles:
      - zfs
      - base
      - nfs
      - permissions
      - user_management
      - smb

  tasks:
  - name: Find all role directories in collection
    find:
      paths: "{{ roles_dir }}"
      file_type: directory
      patterns: "*"
    register: found_roles

  - name: Generate README for each role
    include_tasks: generate_markdown_tasks.yml
    loop: "{{ found_roles.files }}"
    loop_control:
      loop_var: role_dir
    when: role_dir.path | basename not in exclude_roles

    
