---
- name: Install nfs-server
  become: true
  package:
    name: nfs-kernel-server
    state: present

- name: Create nfs root dir if create_share_dirs is true
  become: true
  ansible.builtin.file:
    path: "{{ nfs_share_path }}"
    mode: "0775"
    owner: root
    state: directory
  when: create_share_dirs

- name: Fail if {{ nfs_share_path }} is not present
  block:
    - name: Register {{ nfs_share_path }} directory status to exports_dir
      stat:
        path: "{{ nfs_share_path }}"
      register: exports_dir

    - name: Fail if {{ nfs_share_path }} is not prepared
      fail:
        msg: "{{ nfs_share_path }} must exist before running NFS role"
      when: not exports_dir.stat.exists

- name: Enable and start required services (systemd)
  become: true
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: yes
    state: started
  when: not running_in_molecule | default(false)

- name: Enable and start required services (molecule)
  become: true
  command: service nfs-kernel-server start
  async: 10
  poll: 0
  when: running_in_molecule | default(false)
  changed_when: false

- name: Generate /etc/exports from template
  become: true
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: restart nfs services

