---
# handlers file for roles/zfs
- name: Restart NFS
  become: true
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted

- name: Restart samba
  become: true
  ansible.builtin.systemd:
    name: smbd
    state: restarted